theme = "catppuccin_mocha"

[editor]

# basically theming
true-color = true
undercurl = true
bufferline = "multiple"
color-modes = true

statusline.mode.normal = "normal"
statusline.mode.insert = "insert"
statusline.mode.select = "select"
statusline.separator = "/"
statusline.left = ["mode", "spacer", "file-name", "position", "separator", "total-line-numbers", "spacer", "file-modification-indicator", "read-only-indicator"]
statusline.right = ["spinner", "spacer", "diagnostics", "spacer", "version-control", "spacer", "primary-selection-length", "separator", "selections", "register"]
cursorline = true
gutters.layout = ["diff", "spacer"]
preview-completion-insert = false
scrolloff = 10
scroll-lines = 1
soft-wrap.enable = true

# behaviors
shell = ["fish", "-c"]
auto-pairs = false
lsp.display-messages = true
file-picker.hidden = false
file-picker.ignore = false
file-picker.git-ignore = true

# diagnostics
end-of-line-diagnostics = "info"
inline-diagnostics.cursor-line = "info"

[keys]

# extending defaults
normal.H = "expand_selection"
select.H = "expand_selection"

normal.J = "select_next_sibling"
select.J = "select_next_sibling"

normal.K = "select_prev_sibling"
select.K = "select_prev_sibling"

normal.L = "shrink_selection"
select.L = "shrink_selection"

normal.X = "extend_line_above"
select.X = "extend_line_above"

# nicer selections
normal.esc = ["collapse_selection", "keep_primary_selection"]
normal.i = ["collapse_selection", "insert_mode"]
normal.a = ["collapse_selection", "append_mode"]

select.i = ["collapse_selection", "insert_mode"]
select.a = ["collapse_selection", "append_mode"]

# commands
normal.C-r = [":config-reload", ":reload"]
select.C-r = [":config-reload", ":reload"]
insert.C-r = [":config-reload", ":reload"]

normal.C-q = [":quit"]
select.C-q = [":quit"]
insert.C-q = [":quit"]

# clipboard
normal.C-s = [":w"]
select.C-s = [":w"]
insert.C-s = [":w"]

normal.C-c = [":clipboard-yank"]
select.C-c = [":clipboard-yank"]
insert.C-c = [":clipboard-yank"]

normal.C-x = [":clipboard-yank", "delete_selection_noyank"]
select.C-x = [":clipboard-yank", "delete_selection_noyank"]
insert.C-x = [":clipboard-yank", "delete_selection_noyank"]

normal.C-v = [":clipboard-paste-after", "collapse_selection"]
select.C-v = [":clipboard-paste-replace", "collapse_selection"]
insert.C-v = [":clipboard-paste-after", "collapse_selection"]

normal.C-V = [":clipboard-paste-before", "collapse_selection"]
select.C-V = [":clipboard-paste-replace", "collapse_selection"]
insert.C-V = [":clipboard-paste-before", "collapse_selection"]

normal.C-z = ["undo", "collapse_selection"]
select.C-z = ["undo", "collapse_selection"]
insert.C-z = ["undo", "collapse_selection"]

normal.C-Z = ["redo"]
select.C-Z = ["redo"]
insert.C-Z = ["redo"]

# up and down
normal.A-J = ["extend_line_down", "extend_to_line_bounds"]
select.A-J = ["extend_line_down", "extend_to_line_bounds"]
insert.A-J = ["extend_line_down", "extend_to_line_bounds"]

normal.A-K = ["extend_line_up", "extend_to_line_bounds"]
select.A-K = ["extend_line_up", "extend_to_line_bounds"]
insert.C-K = ["extend_line_up", "extend_to_line_bounds"]

normal.A-j = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked"]
select.A-j = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked"]
insert.A-j = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked"]

normal.A-k = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked"]
select.A-k = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked"]
insert.A-k = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked"]

# disable arrows
normal.A-up = "no_op"
normal.A-down = "no_op"
normal.A-left = "no_op"
normal.A-right = "no_op"
normal.A-S-down = "no_op"
