theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
true-color = true
color-modes = true
scroll-lines = 1
cursorline = true
lsp.display-messages = true
lsp.display-inlay-hints = true
file-picker.hidden = false
file-picker.ignore = false
file-picker.git-ignore = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-absolute-path", "read-only-indicator", "file-modification-indicator", "version-control"]
center = []
right = ["selections", "primary-selection-length", "spacer", "position", "total-line-numbers", "file-encoding", "spacer", "diagnostics", "workspace-diagnostics"]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"
