[tools]
bun = "latest"
node = "latest"
rust = "latest"
gleam = "latest"
python = "3.11"

github-cli = "latest"
yt-dlp = "latest"
helix = "latest"

[plugins]
helix = 'https://github.com/CSergienko/asdf-helix'

[settings]
experimental = true
# not_found_auto_install = true
