[tools]
bun = "latest"
node = "22"
go = "latest"
uv = "latest"
rust = "latest"
gleam = "latest"
github-cli = "latest"
yt-dlp = "latest"
helix = "latest"
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:ripgrep" = "latest"

[alias]
helix = "asdf:https://github.com/CSergienko/asdf-helix"
