[tools]
bun = "latest"
deno = "latest"
node = "latest"
rust = "latest"
gleam = "latest"
python = "3.11"

github-cli = "latest"
yt-dlp = "latest"

"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:du-dust" = "latest"
"cargo:bottom" = "latest"
"cargo:procs" = "latest"
"cargo:bat" = "latest"

 "ubi:helix-editor/helix" = "latest"
